# Generated by Django 5.2.4 on 2026-06-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('ui', 'UI/UX Design'), ('fullstack', 'Full Stack')], default='web', max_length=20),
        ),
    ]
