# Generated by Django 5.2.4 on 2026-07-02 11:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_showcaseproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='active',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='company',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=models.TextField(default='', verbose_name='متن نظر'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='سمت/شرکت'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
    ]
